// Verifique os bytecodes com o comando abaixo:
// node --print-bytecode --print-bytecode-filter=multiplyXByY 8-part/bytecodes.js
function multiplyXByY (obj) {
  return obj.x * obj.y
}

const x = multiplyXByY({ x: 1, y: 2 })
// console.log(x)//2
/*
[generated bytecode for function: multiplyXByY (0x17526fed7251 <SharedFunctionInfo multiplyXByY>)]
Bytecode length: 13
Parameter count 2
Register count 1
Frame size 8
OSR urgency: 0
Bytecode age: 0
  173 S> 0x17526fed7db8 @    0 : 2d 03 00 01       GetNamedProperty a0, [0], [1]
         0x17526fed7dbc @    4 : c4                Star0
  181 E> 0x17526fed7dbd @    5 : 2d 03 01 03       GetNamedProperty a0, [1], [3]
  175 E> 0x17526fed7dc1 @    9 : 3b fa 00          Mul r0, [0]
  182 S> 0x17526fed7dc4 @   12 : a9                Return
Constant pool (size = 2)
0x17526fed7d61: [FixedArray] in OldSpace
 - map: 0x027ad29812e1 <Map>
 - length: 2
           0: 0x223ebd75af49 <String[1]: #x>
           1: 0x223ebd75af61 <String[1]: #y>
Handler Table (size = 0)
Source Position Table (size = 11)
0x17526fed7dc9 <ByteArray[11]>
2
*/
